### ISSUE TITLE
Stage Manager - NameConv.exe

### ISSUE THREAD

**Issue by Roadhog360** [libertyernie/BrawlManagers#12]
It says I need this file to generate nameplates... and also isn't included in the download and you haven't provided any information whatsoever as to how to get this file.

**Comment by libertyernie** [comment]
Are you using an old version? I have version 3.9 and I don't see any reference to NameConv.exe in the source code.

I can generate nameplates by clicking the "Generate name" button after selecting a stage. It asks for a name then asks which font I want to use.

**Comment by Roadhog360** [comment]
Thank you, that seems to have worked. I thought I updated, but apparantly not.

**Comment by Roadhog360** [comment]
As a side note I got it wrong. It was genname, not nameconv.
