### ISSUE TITLE
Costume Manager always crashes.

### ISSUE THREAD

**Issue by Delta-Kuro** [libertyernie/BrawlManagers#4]
I can never get it open because it crashes within two seconds of opening it.

**Comment by libertyernie** [comment]
Does Stage Manager work?
Also, are you on 32-bit or 64-bit OS, and is .NET Framework 4 or newer installed?

**Comment by Delta-Kuro** [comment]
Everything except costume manager works. Also, 64-bit, and yes it is.

**Comment by Delta-Kuro** [comment]
Lastly, when checking through the task manager, the process is open for a few seconds before auto-closing.

**Comment by Delta-Kuro** [comment]
Nevermind, Windows XP compatibility mode fixed it.
